site_name: My Docs
site_url: https://SergioCortes22.github.com/Pruebas1/
docs_dir: 'docs_src'
site_dir: 'docs'

nav:
  - Home: index.md
  - Guía de Instalación Windows 11: Guía_Instalación_Windows_11.md
  - Especificaciones Técnicas iPhone 16: Especificaciones_Técnicas_iPhone_16.md
  - Descarga de la documentación en formato PDF: PDF.md

theme: readthedocs
